development:
  adapter: postgresql
  database: heysenior_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: heysenior_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: heysenior_production
  pool: 5
  timeout: 5000